# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: similarity.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'similarity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10similarity.proto\x12\nsimilarity\"C\n\x11SimilarityRequest\x12\x16\n\x0eimage_base64_1\x18\x01 \x01(\t\x12\x16\n\x0eimage_base64_2\x18\x02 \x01(\t\"(\n\x12SimilarityResponse\x12\x12\n\nsimilarity\x18\x01 \x01(\x02\x32i\n\x11SimilarityService\x12T\n\x13\x43\x61lculateSimilarity\x12\x1d.similarity.SimilarityRequest\x1a\x1e.similarity.SimilarityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'similarity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMILARITYREQUEST']._serialized_start=32
  _globals['_SIMILARITYREQUEST']._serialized_end=99
  _globals['_SIMILARITYRESPONSE']._serialized_start=101
  _globals['_SIMILARITYRESPONSE']._serialized_end=141
  _globals['_SIMILARITYSERVICE']._serialized_start=143
  _globals['_SIMILARITYSERVICE']._serialized_end=248
# @@protoc_insertion_point(module_scope)
