// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: similarity.proto

package similarity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimilarityService_CalculateSimilarity_FullMethodName = "/similarity.SimilarityService/CalculateSimilarity"
)

// SimilarityServiceClient is the client API for SimilarityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimilarityServiceClient interface {
	CalculateSimilarity(ctx context.Context, in *SimilarityRequest, opts ...grpc.CallOption) (*SimilarityResponse, error)
}

type similarityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimilarityServiceClient(cc grpc.ClientConnInterface) SimilarityServiceClient {
	return &similarityServiceClient{cc}
}

func (c *similarityServiceClient) CalculateSimilarity(ctx context.Context, in *SimilarityRequest, opts ...grpc.CallOption) (*SimilarityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimilarityResponse)
	err := c.cc.Invoke(ctx, SimilarityService_CalculateSimilarity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimilarityServiceServer is the server API for SimilarityService service.
// All implementations must embed UnimplementedSimilarityServiceServer
// for forward compatibility.
type SimilarityServiceServer interface {
	CalculateSimilarity(context.Context, *SimilarityRequest) (*SimilarityResponse, error)
	mustEmbedUnimplementedSimilarityServiceServer()
}

// UnimplementedSimilarityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimilarityServiceServer struct{}

func (UnimplementedSimilarityServiceServer) CalculateSimilarity(context.Context, *SimilarityRequest) (*SimilarityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateSimilarity not implemented")
}
func (UnimplementedSimilarityServiceServer) mustEmbedUnimplementedSimilarityServiceServer() {}
func (UnimplementedSimilarityServiceServer) testEmbeddedByValue()                           {}

// UnsafeSimilarityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimilarityServiceServer will
// result in compilation errors.
type UnsafeSimilarityServiceServer interface {
	mustEmbedUnimplementedSimilarityServiceServer()
}

func RegisterSimilarityServiceServer(s grpc.ServiceRegistrar, srv SimilarityServiceServer) {
	// If the following call pancis, it indicates UnimplementedSimilarityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimilarityService_ServiceDesc, srv)
}

func _SimilarityService_CalculateSimilarity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimilarityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimilarityServiceServer).CalculateSimilarity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimilarityService_CalculateSimilarity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimilarityServiceServer).CalculateSimilarity(ctx, req.(*SimilarityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SimilarityService_ServiceDesc is the grpc.ServiceDesc for SimilarityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimilarityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "similarity.SimilarityService",
	HandlerType: (*SimilarityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateSimilarity",
			Handler:    _SimilarityService_CalculateSimilarity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "similarity.proto",
}
